defmodule Year2024.Day08Test do
  use ExUnit.Case, async: true

  @input_path Path.expand("../../priv/year2024/day08/input.txt", __DIR__)

  describe "part 1" do
    test "works with the sample input" do
      # Use the first example from the sample file (before the first "---")
      sample = """
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
      """
      assert Year2024.Day08.part(1, sample) == 14
    end

    @tag :skip
    test "works with the real input" do
      input = File.read!(@input_path)
      assert Year2024.Day08.part(1, input) == :not_implemented
    end
  end

  describe "part 2" do
    test "works with the sample input" do
      # Use the first example from the sample file (before the first "---")
      sample = """
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
      """
      assert Year2024.Day08.part(2, sample) == 34
    end

    @tag :skip
    test "works with the real input" do
      input = File.read!(@input_path)
      assert Year2024.Day08.part(2, input) == :not_implemented
    end
  end

end
